<a href="https://colab.research.google.com/github/maribelalay18/-Artificial-Intelligence/blob/main/martes05_11_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
matrixA=np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(matrixA.shape)

(3, 4)


In [6]:
matrixA

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [8]:
print(matrixA[1:,1:3])

[[22 23]
 [32 33]]


In [7]:

# Create a 4x3 matrix with random integers between 0 and 9
matrix = np.random.randint(0, 10, size=(4, 3))

# Print the matrix
print(matrix)

[[2 2 1]
 [4 0 0]
 [8 5 5]
 [5 9 7]]


In [9]:
print(matrix.shape)

(4, 3)


In [14]:
print(matrix)
col_indices=np.array([0,1,2])
row_indices=np.array([1,2])
for row,col in zip(row_indices,col_indices):
    # print(row," ",col)
    print(matrix[row,col])


[[2 2 1]
 [4 0 0]
 [8 5 5]
 [5 9 7]]
4
5


In [16]:
mask=matrix>7
print(mask)

[[False False False]
 [False False False]
 [ True False False]
 [False  True False]]


In [17]:
print(matrix[mask])

[8 9]


In [18]:
print(matrix[matrix>7])

[8 9]


agregar 100 a los elementosa que sean pares


In [28]:
matrix[matrix%2==0] += 100
print(matrix)

[[202 202   1]
 [204 200 200]
 [208 105 105]
 [105   9 107]]


In [29]:
matrix[(matrix > 3) & (matrix < 9)] += 100
print(matrix)

[[202 202   1]
 [204 200 200]
 [208 105 105]
 [105   9 107]]


In [31]:
print(matrix)

[[202 202   1]
 [204 200 200]
 [208 105 105]
 [105   9 107]]


In [30]:
matrixC=np.random.rand(2,2)
print(matrixC)

[[0.30084735 0.30043717]
 [0.35214611 0.3440583 ]]


In [37]:
filter=(matrix>3) & (matrix<9)
matrix[filter]+=100
print(matrix)

[[202 202   1]
 [204 200 200]
 [208 105 105]
 [105   9 107]]


In [39]:
matrixA1=np.random.randint(0,10,size=(4,3))
matrixA2=np.random.randint(0,10,size=(4,3))
print(matrixA1)
print	(matrixA2)

[[8 6 4]
 [5 6 6]
 [4 5 5]
 [7 7 6]]
[[4 9 6]
 [6 8 8]
 [8 9 4]
 [8 5 1]]


In [40]:
print(matrixA1+matrixA2)
print(matrixA1-matrixA2)
print(matrixA1*matrixA2)
print(matrixA1/matrixA2)

[[12 15 10]
 [11 14 14]
 [12 14  9]
 [15 12  7]]
[[ 4 -3 -2]
 [-1 -2 -2]
 [-4 -4  1]
 [-1  2  5]]
[[32 54 24]
 [30 48 48]
 [32 45 20]
 [56 35  6]]
[[2.         0.66666667 0.66666667]
 [0.83333333 0.75       0.75      ]
 [0.5        0.55555556 1.25      ]
 [0.875      1.4        6.        ]]


In [41]:
print(matrixA1)

[[8 6 4]
 [5 6 6]
 [4 5 5]
 [7 7 6]]


In [42]:
print(np.sqrt(matrixA1))

[[2.82842712 2.44948974 2.        ]
 [2.23606798 2.44948974 2.44948974]
 [2.         2.23606798 2.23606798]
 [2.64575131 2.64575131 2.44948974]]


In [43]:
matrixA1=np.random.randint(0,10,size=(2,5))
matrixA2=np.random.randint(0,10,size=(3,2))
print(matrixA1)
print(matrixA2)

[[1 9 4 4 1]
 [8 0 1 7 5]]
[[7 6]
 [4 5]
 [9 4]]


In [44]:
print(np.mean(matrixA1))

4.0


In [46]:
print(matrixA1.mean (axis=1))

[3.8 4.2]


In [48]:
print(matrixA1.mean(axis=0))

[4.5 4.5 2.5 5.5 3. ]


In [50]:
print(np.median(matrixA1))

4.0


In [51]:
print(matrixA1.sum())

40


In [52]:
print(matrixA1.max())

9


concatenar para modificar la extencion de la matriz

In [53]:
start=np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [54]:
add_rows=np.array([1,2,3])
print(add_rows.shape)

(3,)


In [55]:
y=start+add_rows
print(y)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [56]:
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [57]:
col_rows=np.array([1,2,3,4])
print(col_rows.shape)

(4,)


In [72]:
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [73]:
print (start)
tmp=col_rows.T
y2=start+tmp
print(y2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

crear una matriz de 2*2  que el valor minimo sea 2 y el maximo 50

In [68]:
y1=np.random.randint(low=2, high=50,size=(2,2))
y2=np.random.randint(low=2, high=50,size=(2,2))
print(y1)
print(y2)

[[49 13]
 [14 39]]
[[18 26]
 [34  6]]


In [69]:
np.vstack((y1,y2))

array([[49, 13],
       [14, 39],
       [18, 26],
       [34,  6]])