<a href="https://colab.research.google.com/github/maribelalay18/-Artificial-Intelligence/blob/main/martes29_10_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy LIBRARY

In [3]:
import numpy as np

In [4]:
print(np.__version__)

1.26.4


In [5]:
myArray = np.array([1,2,3,4,5])
print(myArray)

[1 2 3 4 5]


In [6]:
print(type(myArray))

<class 'numpy.ndarray'>


1. dimension de matriz
2. muestra el tercer numero de la lista
3.cambia el numero de la tercer lista por el 9
4. mostrar

In [9]:
print(myArray.shape)
print(myArray[2])
myArray[2] = 9
print(myArray)

(5,)
3
[1 2 9 4 5]


In [11]:
myArray1 = np.array([[1,2,3],[4,5,6]])
print(myArray1)
print(myArray.shape)
#

[[1 2 3]
 [4 5 6]]
(2, 3)


In [13]:
myArray3=np.zeros((5,5))
print(myArray3)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [19]:
myArray4=np.full((3,6),10)
print(myArray4)
myArray5=np.eye(5)
print(myArray5)

myArray6=np.ones((5,5))
print(myArray6)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [20]:
myArray7=np.random.random((5,5))
print(myArray7)

[[0.50782053 0.33011009 0.55013693 0.55492277 0.2044956 ]
 [0.82255319 0.1269125  0.04445333 0.66174623 0.84257094]
 [0.32284006 0.83369774 0.23356522 0.41608489 0.26007357]
 [0.72423485 0.81551896 0.42050199 0.04950631 0.09768275]
 [0.26108712 0.63699375 0.88932682 0.43557427 0.08288817]]


In [23]:
myArray8=np.random.randint(100,size=(5,5))
print(myArray8)

[[ 0 69 66  6 94]
 [ 6 79 72 33 28]
 [41 30 90 70 20]
 [75 30 23 12 34]
 [31  7 21  1 76]]


In [24]:
newMatrix=myArray8[:2,:2]
print(newMatrix)

[[ 0 69]
 [ 6 79]]


CAMBIA EL VALOR DEL MEDIO

In [27]:
myArray8[2,2]=1000
print(myArray8)

[[ 100   69   66    6   94]
 [   6   79   72   33   28]
 [  41   30 1000   70   20]
 [  75   30   23   12   34]
 [  31    7   21    1   76]]


In [28]:
print(myArray8[2,:])

[  41   30 1000   70   20]


MUESTRA DE CUANTAS DIMENSIONES ES LA MATRIZ

In [30]:
print(myArray8[:,2].shape)

(5,)


In [33]:
subMatrix=myArray8[1:4,1:4]
print(subMatrix)

[[  79   72   33]
 [  30 1000   70]
 [  30   23   12]]
